spring:
  profiles:
    include:
      - ticket
  application:
    name: wolfdesk
  datasource:
    url: jdbc:postgresql://localhost:5432/wolfdesk
    username: wolfdesk
    password: wolfdesk

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

  data:
    redis:
      host: localhost
      port: 6379

  modulith:
    events:
      jdbc:
        schema-initialization:
          enabled: true

  docker:
    compose:
      skip:
        in-tests: false
      lifecycle-management: start_and_stop
jwt:
  secret-key: ${SECRET_KEY:05ae30dc50edb5c764b339b84b26838e2d394acf56a0709189758e75c8448fa0}
  expired: 1h
