spring:
  application:
    name: wolfdesk
  datasource:
    url: jdbc:h2:mem:${spring.application.name}
    username: root
  h2:
    console:
      enabled: true

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

jwt:
  secret-key: ${SECRET_KEY:s3cr3tK3y!Th1sIsARandomStringWith64CharactersIncludingSecretKey3}
  expired: 5m
