spring:
  profiles:
    include:
      - ticket
  application:
    name: wolfdesk
  datasource:
    url: jdbc:h2:mem:${spring.application.name}
    username: root
  h2:
    console:
      enabled: true

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

  modulith:
    events:
      jdbc:
        schema-initialization:
          enabled: true
jwt:
  secret-key: ${SECRET_KEY:05ae30dc50edb5c764b339b84b26838e2d394acf56a0709189758e75c8448fa0}
  expired: 5m
