services:
  database:
    image: postgres:15.2
    ports:
      - '5432'
    environment:
      - 'POSTGRES_USER=wolfdesk'
      - 'POSTGRES_DB=wolfdesk'
      - 'POSTGRES_PASSWORD=wolfdesk'

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  broker:
    image: confluentinc/cp-kafka:7.8.0
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      # Replace CLUSTER_ID with a unique base64 UUID using "bin/kafka-storage.sh random-uuid"
      # See https://docs.confluent.io/kafka/operations-tools/kafka-tools.html#kafka-storage-sh
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'

  spicedb:
    image: authzed/spicedb:v1.39.1
    depends_on:
      migrate:
        condition: service_completed_successfully
    ports:
      - "50051:50051"
    command: serve
    environment:
      TZ: "Asia/Seoul"

      SPICEDB_GRPC_ENABLED: "true"
      SPICEDB_GRPC_ADDR: ":50051"
      SPICEDB_GRPC_PRESHARED_KEY: "wolfdesk"

      SPICEDB_DATASTORE_ENGINE: "postgres"
      SPICEDB_DATASTORE_CONN_URI: "postgres://wolfdesk:wolfdesk@database:5432/wolfdesk?sslmode=disable"

  migrate:
    image: authzed/spicedb:v1.39.1
    restart: on-failure
    depends_on:
      - database
    command: migrate head
    environment:
      TZ: "Asia/Seoul"
      SPICEDB_DATASTORE_ENGINE: "postgres"
      SPICEDB_DATASTORE_CONN_URI: "postgres://wolfdesk:wolfdesk@database:5432/wolfdesk?sslmode=disable"
